// Diccionario completo español-inglés para IA artística
const diccionario = {
  // Personas y características físicas
  'mujer': 'woman',
  'hombre': 'man', 
  'niño': 'boy',
  'niña': 'girl',
  'bebé': 'baby',
  'persona': 'person',
  'gente': 'people',
  'joven': 'young',
  'adulto': 'adult',
  'anciano': 'elderly man',
  'anciana': 'elderly woman',
  'adolescente': 'teenager',
  'hermoso': 'beautiful',
  'hermosa': 'beautiful',
  'guapo': 'handsome',
  'guapa': 'beautiful',
  'atractivo': 'attractive',
  'elegante': 'elegant',
  'musculoso': 'muscular',
  'delgado': 'thin',
  'gordo': 'fat',
  'alto': 'tall',
  'bajo': 'short',
  
  // Cabello
  'cabello largo': 'long hair',
  'cabello corto': 'short hair',
  'cabello rizado': 'curly hair',
  'cabello liso': 'straight hair',
  'cabello ondulado': 'wavy hair',
  'rubia': 'blonde',
  'morena': 'brunette',
  'pelirroja': 'redhead',
  'cabello negro': 'black hair',
  'cabello castaño': 'brown hair',
  'cabello gris': 'gray hair',
  'cabello blanco': 'white hair',
  'calvo': 'bald',
  'barba': 'beard',
  'bigote': 'mustache',
  
  // Ojos
  'ojos azules': 'blue eyes',
  'ojos verdes': 'green eyes',
  'ojos marrones': 'brown eyes',
  'ojos negros': 'black eyes',
  'ojos grises': 'gray eyes',
  'ojos grandes': 'big eyes',
  'ojos pequeños': 'small eyes',
  
  // Expresiones y poses
  'sonriendo': 'smiling',
  'riendo': 'laughing',
  'triste': 'sad',
  'feliz': 'happy',
  'serio': 'serious',
  'enfadado': 'angry',
  'sorprendido': 'surprised',
  'pensativo': 'thoughtful',
  'sentado': 'sitting',
  'de pie': 'standing',
  'caminando': 'walking',
  'corriendo': 'running',
  'saltando': 'jumping',
  'bailando': 'dancing',
  'durmiendo': 'sleeping',
  'mirando': 'looking',
  'mirando hacia arriba': 'looking up',
  'mirando hacia abajo': 'looking down',
  'mirando al cielo': 'looking at the sky',
  'mirando a la cámara': 'looking at camera',
  'brazos cruzados': 'arms crossed',
  'manos en las caderas': 'hands on hips',
  
  // Ropa y accesorios
  'con vestido': 'wearing a dress',
  'con camisa': 'wearing a shirt',
  'con pantalones': 'wearing pants',
  'con falda': 'wearing a skirt',
  'con chaqueta': 'wearing a jacket',
  'con abrigo': 'wearing a coat',
  'con sombrero': 'wearing a hat',
  'con gafas': 'wearing glasses',
  'con collar': 'wearing a necklace',
  'con pendientes': 'wearing earrings',
  'con anillo': 'wearing a ring',
  'descalzo': 'barefoot',
  'con zapatos': 'wearing shoes',
  'con botas': 'wearing boots',
  'con tacones': 'wearing heels',
  'con uniforme': 'wearing uniform',
  'con traje': 'wearing a suit',
  'con bikini': 'wearing bikini',
  'con bañador': 'wearing swimsuit',
  
  // Animales
  'gato': 'cat',
  'perro': 'dog',
  'caballo': 'horse',
  'pájaro': 'bird',
  'pez': 'fish',
  'león': 'lion',
  'tigre': 'tiger',
  'oso': 'bear',
  'lobo': 'wolf',
  'elefante': 'elephant',
  'mono': 'monkey',
  'conejo': 'rabbit',
  'ratón': 'mouse',
  'serpiente': 'snake',
  'mariposa': 'butterfly',
  'abeja': 'bee',
  'águila': 'eagle',
  'búho': 'owl',
  'delfín': 'dolphin',
  'ballena': 'whale',
  'tiburón': 'shark',
  
  // Lugares y ambientes
  'en la playa': 'on the beach',
  'en el bosque': 'in the forest',
  'en la ciudad': 'in the city',
  'en el campo': 'in the countryside',
  'en la montaña': 'in the mountains',
  'en el desierto': 'in the desert',
  'en el jardín': 'in the garden',
  'en el parque': 'in the park',
  'en casa': 'at home',
  'en la oficina': 'in the office',
  'en la escuela': 'at school',
  'en el hospital': 'in the hospital',
  'en el restaurante': 'in the restaurant',
  'en la iglesia': 'in the church',
  'en el museo': 'in the museum',
  'en el gimnasio': 'in the gym',
  'en el lago': 'at the lake',
  'en el río': 'by the river',
  'en el mar': 'at sea',
  'en el océano': 'in the ocean',
  'en la piscina': 'in the pool',
  'en el espacio': 'in space',
  'en el cielo': 'in the sky',
  'bajo el agua': 'underwater',
  'en una cueva': 'in a cave',
  'en un castillo': 'in a castle',
  'en una casa': 'in a house',
  
  // Tiempo y clima
  'atardecer': 'sunset',
  'amanecer': 'sunrise',
  'mediodía': 'midday',
  'medianoche': 'midnight',
  'noche': 'night',
  'día': 'day',
  'mañana': 'morning',
  'tarde': 'afternoon',
  'lluvia': 'rain',
  'sol': 'sun',
  'nieve': 'snow',
  'viento': 'wind',
  'tormenta': 'storm',
  'niebla': 'fog',
  'nublado': 'cloudy',
  'despejado': 'clear',
  'calor': 'heat',
  'frío': 'cold',
  'primavera': 'spring',
  'verano': 'summer',
  'otoño': 'autumn',
  'invierno': 'winter',
  
  // Colores
  'rojo': 'red',
  'azul': 'blue',
  'verde': 'green',
  'amarillo': 'yellow',
  'naranja': 'orange',
  'morado': 'purple',
  'rosa': 'pink',
  'negro': 'black',
  'blanco': 'white',
  'gris': 'gray',
  'marrón': 'brown',
  'dorado': 'golden',
  'plateado': 'silver',
  'colorido': 'colorful',
  'multicolor': 'multicolored',
  
  // Estilos artísticos
  'realista': 'realistic',
  'hiperrealista': 'hyperrealistic',
  'fantasía': 'fantasy',
  'anime': 'anime',
  'manga': 'manga',
  'cartoon': 'cartoon',
  'abstracto': 'abstract',
  'surrealista': 'surrealist',
  'impresionista': 'impressionist',
  'cubista': 'cubist',
  'pop art': 'pop art',
  'art nouveau': 'art nouveau',
  'steampunk': 'steampunk',
  'cyberpunk': 'cyberpunk',
  'gótico': 'gothic',
  'medieval': 'medieval',
  'victoriano': 'victorian',
  'barroco': 'baroque',
  'renacentista': 'renaissance',
  'moderno': 'modern',
  'contemporáneo': 'contemporary',
  'minimalista': 'minimalist',
  'vintage': 'vintage',
  'retro': 'retro',
  
  // Técnicas y medios
  'pintura': 'painting',
  'pintura al óleo': 'oil painting',
  'acuarela': 'watercolor',
  'dibujo': 'drawing',
  'sketch': 'sketch',
  'boceto': 'sketch',
  'ilustración': 'illustration',
  'arte digital': 'digital art',
  'pintura digital': 'digital painting',
  'fotografía': 'photography',
  'foto': 'photo',
  'render 3d': '3d render',
  'modelado 3d': '3d modeling',
  'escultura': 'sculpture',
  'grabado': 'engraving',
  'collage': 'collage',
  'mosaico': 'mosaic',
  
  // Calidad y detalles técnicos
  'alta calidad': 'high quality',
  'ultra alta calidad': 'ultra high quality',
  'calidad profesional': 'professional quality',
  'obra maestra': 'masterpiece',
  'detallado': 'detailed',
  'muy detallado': 'highly detailed',
  'ultra detallado': 'ultra detailed',
  'preciso': 'precise',
  'nítido': 'sharp',
  'enfocado': 'focused',
  'desenfocado': 'blurred',
  'borroso': 'blurry',
  'claro': 'clear',
  '4k': '4k',
  '8k': '8k',
  'alta resolución': 'high resolution',
  'hd': 'hd',
  'uhd': 'uhd',
  
  // Iluminación
  'luz': 'light',
  'luz suave': 'soft light',
  'luz dura': 'hard light',
  'luz natural': 'natural light',
  'luz artificial': 'artificial light',
  'luz cálida': 'warm light',
  'luz fría': 'cool light',
  'contraluz': 'backlight',
  'iluminación dramática': 'dramatic lighting',
  'iluminación cinematográfica': 'cinematic lighting',
  'sombra': 'shadow',
  'sombras suaves': 'soft shadows',
  'sombras duras': 'hard shadows',
  'reflejo': 'reflection',
  'brillo': 'brightness',
  'contraste': 'contrast',
  'alto contraste': 'high contrast',
  'bajo contraste': 'low contrast',
  'saturado': 'saturated',
  'desaturado': 'desaturated',
  'vibrante': 'vibrant',
  'apagado': 'muted',
  'brillante': 'bright',
  'oscuro': 'dark',
  'luminoso': 'luminous',
  'resplandeciente': 'glowing',
  
  // Composición y perspectiva
  'primer plano': 'close-up',
  'plano medio': 'medium shot',
  'plano general': 'wide shot',
  'gran angular': 'wide angle',
  'teleobjetivo': 'telephoto',
  'macro': 'macro',
  'perspectiva aérea': 'aerial view',
  'vista de pájaro': 'bird\'s eye view',
  'vista desde abajo': 'low angle',
  'vista desde arriba': 'high angle',
  'perfil': 'profile',
  'frontal': 'frontal',
  'tres cuartos': 'three quarters',
  'centrado': 'centered',
  'descentrado': 'off-center',
  'simétrico': 'symmetric',
  'asimétrico': 'asymmetric',
  
  // Texturas y materiales
  'textura': 'texture',
  'suave': 'smooth',
  'rugoso': 'rough',
  'áspero': 'coarse',
  'liso': 'smooth',
  'brillante': 'shiny',
  'mate': 'matte',
  'satinado': 'satin',
  'metálico': 'metallic',
  'cristal': 'crystal',
  'vidrio': 'glass',
  'madera': 'wood',
  'piedra': 'stone',
  'mármol': 'marble',
  'tela': 'fabric',
  'seda': 'silk',
  'terciopelo': 'velvet',
  'cuero': 'leather',
  'plástico': 'plastic',
  'papel': 'paper',
  'agua': 'water',
  'fuego': 'fire',
  'humo': 'smoke',
  'vapor': 'steam',
  'niebla': 'mist',
  'polvo': 'dust',
  'arena': 'sand',
  'tierra': 'earth',
  'barro': 'mud',
  'nieve': 'snow',
  'hielo': 'ice',
  
  // Naturaleza
  'naturaleza': 'nature',
  'paisaje': 'landscape',
  'árbol': 'tree',
  'bosque': 'forest',
  'selva': 'jungle',
  'flor': 'flower',
  'rosa': 'rose',
  'girasol': 'sunflower',
  'hierba': 'grass',
  'césped': 'lawn',
  'hoja': 'leaf',
  'rama': 'branch',
  'tronco': 'trunk',
  'raíz': 'root',
  'montaña': 'mountain',
  'colina': 'hill',
  'valle': 'valley',
  'río': 'river',
  'lago': 'lake',
  'mar': 'sea',
  'océano': 'ocean',
  'playa': 'beach',
  'costa': 'coast',
  'isla': 'island',
  'desierto': 'desert',
  'oasis': 'oasis',
  'cascada': 'waterfall',
  'cueva': 'cave',
  'roca': 'rock',
  'piedra': 'stone',
  'arena': 'sand',
  'tierra': 'soil',
  'cielo': 'sky',
  'nube': 'cloud',
  'estrella': 'star',
  'luna': 'moon',
  'planeta': 'planet',
  'galaxia': 'galaxy',
  'arco iris': 'rainbow',
  
  // Arquitectura y objetos
  'casa': 'house',
  'edificio': 'building',
  'castillo': 'castle',
  'iglesia': 'church',
  'catedral': 'cathedral',
  'torre': 'tower',
  'puente': 'bridge',
  'carretera': 'road',
  'calle': 'street',
  'plaza': 'square',
  'mercado': 'market',
  'tienda': 'shop',
  'ventana': 'window',
  'puerta': 'door',
  'techo': 'roof',
  'pared': 'wall',
  'columna': 'column',
  'escalera': 'stairs',
  'balcón': 'balcony',
  'jardín': 'garden',
  'patio': 'patio',
  'terraza': 'terrace',
  'fuente': 'fountain',
  'estatua': 'statue',
  'monumento': 'monument',
  
  // Vehículos
  'coche': 'car',
  'moto': 'motorcycle',
  'bicicleta': 'bicycle',
  'camión': 'truck',
  'autobús': 'bus',
  'tren': 'train',
  'avión': 'airplane',
  'helicóptero': 'helicopter',
  'barco': 'boat',
  'nave espacial': 'spaceship',
  
  // Emociones y conceptos
  'amor': 'love',
  'paz': 'peace',
  'guerra': 'war',
  'libertad': 'freedom',
  'esperanza': 'hope',
  'miedo': 'fear',
  'alegría': 'joy',
  'tristeza': 'sadness',
  'ira': 'anger',
  'sorpresa': 'surprise',
  'calma': 'calm',
  'caos': 'chaos',
  'orden': 'order',
  'misterio': 'mystery',
  'magia': 'magic',
  'poder': 'power',
  'energía': 'energy',
  'fuerza': 'strength',
  'debilidad': 'weakness',
  'velocidad': 'speed',
  'lentitud': 'slowness',
  
  // Comida
  'comida': 'food',
  'fruta': 'fruit',
  'manzana': 'apple',
  'naranja': 'orange',
  'plátano': 'banana',
  'uva': 'grape',
  'fresa': 'strawberry',
  'verdura': 'vegetable',
  'pan': 'bread',
  'carne': 'meat',
  'pescado': 'fish',
  'pastel': 'cake',
  'helado': 'ice cream',
  'chocolate': 'chocolate',
  'café': 'coffee',
  'té': 'tea',
  'agua': 'water',
  'vino': 'wine',
  'cerveza': 'beer',
  
  // Preposiciones y conectores
  'y': 'and',
  'o': 'or',
  'pero': 'but',
  'con': 'with',
  'sin': 'without',
  'sobre': 'on',
  'bajo': 'under',
  'en': 'in',
  'dentro de': 'inside',
  'fuera de': 'outside',
  'cerca de': 'near',
  'lejos de': 'far from',
  'delante de': 'in front of',
  'detrás de': 'behind',
  'al lado de': 'next to',
  'entre': 'between',
  'durante': 'during',
  'antes': 'before',
  'después': 'after',
  'mientras': 'while',
  'cuando': 'when',
  'donde': 'where',
  'como': 'like',
  'muy': 'very',
  'más': 'more',
  'menos': 'less',
  'mucho': 'much',
  'poco': 'little',
  'todo': 'all',
  'nada': 'nothing',
  'algo': 'something',
  'alguien': 'someone',
  'nadie': 'nobody',
  
  // Artículos y determinantes
  'el': '',
  'la': '',
  'los': '',
  'las': '',
  'un': 'a',
  'una': 'a',
  'unos': 'some',
  'unas': 'some',
  'este': 'this',
  'esta': 'this',
  'estos': 'these',
  'estas': 'these',
  'ese': 'that',
  'esa': 'that',
  'esos': 'those',
  'esas': 'those',
  'mi': 'my',
  'tu': 'your',
  'su': 'his',
  'nuestro': 'our',
  'vuestro': 'your',
  'su': 'their',
  
  // Conceptos artísticos avanzados
  'composición': 'composition',
  'equilibrio': 'balance',
  'armonía': 'harmony',
  'ritmo': 'rhythm',
  'movimiento': 'movement',
  'profundidad': 'depth',
  'perspectiva': 'perspective',
  'proporción': 'proportion',
  'escala': 'scale',
  'énfasis': 'emphasis',
  'contraste': 'contrast',
  'unidad': 'unity',
  'variedad': 'variety',
  'patrón': 'pattern',
  'repetición': 'repetition',
  'línea': 'line',
  'forma': 'shape',
  'volumen': 'volume',
  'espacio': 'space',
  'color': 'color',
  'tono': 'tone',
  'matiz': 'hue',
  'saturación': 'saturation',
  'valor': 'value',
  'temperatura': 'temperature',
  
  // Términos técnicos de fotografía
  'bokeh': 'bokeh',
  'profundidad de campo': 'depth of field',
  'apertura': 'aperture',
  'velocidad de obturación': 'shutter speed',
  'iso': 'iso',
  'exposición': 'exposure',
  'sobreexpuesto': 'overexposed',
  'subexpuesto': 'underexposed',
  'ruido': 'noise',
  'grano': 'grain',
  'viñeteado': 'vignetting',
  'aberración cromática': 'chromatic aberration',
  'distorsión': 'distortion',
  
  // Géneros cinematográficos y artísticos
  'drama': 'drama',
  'comedia': 'comedy',
  'terror': 'horror',
  'suspense': 'thriller',
  'acción': 'action',
  'aventura': 'adventure',
  'romance': 'romance',
  'ciencia ficción': 'science fiction',
  'fantasía épica': 'epic fantasy',
  'western': 'western',
  'noir': 'noir',
  'documental': 'documentary',
  
  // Términos de videojuegos y cómic
  'pixel art': 'pixel art',
  'cel shading': 'cel shading',
  'low poly': 'low poly',
  'high poly': 'high poly',
  'isométrico': 'isometric',
  'sprite': 'sprite',
  'concept art': 'concept art',
  'fan art': 'fan art',
  'cómic': 'comic',
  'manga': 'manga',
  'manhwa': 'manhwa',
  'webtoon': 'webtoon',
  
  // Efectos especiales y post-procesado
  'efecto': 'effect',
  'filtro': 'filter',
  'desenfoque': 'blur',
  'desenfoque gaussiano': 'gaussian blur',
  'desenfoque de movimiento': 'motion blur',
  'viñeta': 'vignette',
  'aberración': 'aberration',
  'distorsión de lente': 'lens distortion',
  'bloom': 'bloom',
  'hdr': 'hdr',
  'tone mapping': 'tone mapping',
  'color grading': 'color grading',
  'corrección de color': 'color correction',
  'saturación': 'saturation',
  'desaturación': 'desaturation',
  'sepia': 'sepia',
  'monocromo': 'monochrome',
  'blanco y negro': 'black and white',
  
  // Palabras técnicas específicas para IA
  'prompt': 'prompt',
  'seed': 'seed',
  'steps': 'steps',
  'cfg scale': 'cfg scale',
  'sampling': 'sampling',
  'denoising': 'denoising',
  'upscaling': 'upscaling',
  'inpainting': 'inpainting',
  'outpainting': 'outpainting',
  'img2img': 'img2img',
  'txt2img': 'txt2img',
  'controlnet': 'controlnet',
  'lora': 'lora',
  'checkpoint': 'checkpoint',
  'modelo': 'model',
  'embeddings': 'embeddings',
  'negative prompt': 'negative prompt',
  'weights': 'weights',
  'strength': 'strength'
};

// Exportar para uso en otros archivos
if (typeof module !== 'undefined' && module.exports) {
  module.exports = diccionario;
}
